{
    perform: true,
    alwaysRequireAssignee: false,
    labelsRequiringAssignee: [ feature-request ],
    autoAssignees: {
        emmet: [ chrmarti ],
        integrated-terminal: [ chrmarti ]
    }
}