{
    perform: true,
    alwaysRequireAssignee: false,
    labelsRequiringAssignee: [],
    autoAssignees: {
        accessibility: [],
        api: [],
        css-less-sass: [],
        debug: [],
        editor: [],
        editor-brackets: [],
        editor-clipboard: [],
        editor-colors: [],
        editor-contrib: [],
        editor-core: [],
        editor-find-widget: [],
        editor-folding: [],
        editor-ime: [],
        editor-indentation: [],
        editor-input: [],
        editor-minimap: [],
        editor-multicursor: [],
        editor-wrapping: [],
        emmet: [chrmarti, vscodebot],
        error-list: [],
        extensions: [],
        git: [],
        hot-exit: [],
        html: [],
        i18n: [],
        install-update: [],
        integrated-terminal: [],
        javascript: [],
        json: [],
        languages basic: [],
        markdown: [],
        perf-profile: [],
        php: [],
        search: [],
        tasks: [],
        typescript: [],
        workbench: [],
    }
}
