{
    perform: true,
    alwaysRequireAssignee: true,
    labelsRequiringAssignee: [ feature-request ],
    autoAssignees: {
        emmet: [ chrmarti ],
        integrated-terminal: [ chrmarti ]
    }
}