{
    perform: true,
    commands: [
        # Proposed
        {
            type: 'label',
            name: 'question',
            executeForExistingLabels: false,
            action: 'close',
            comment: "This issue has been closed because it represents a question. Questions are better addressed on [StackOverflow](https://stackoverflow.com/questions/tagged/vscode?sort=votes&pageSize=50). See also our [issue tracking](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md) guidelines.\n\nThank you for your contributions."
        },
        {
            type: 'label',
            name: 'extension-candidate',
            executeForExistingLabels: false,
            action: 'close',
            comment: "This issue has been closed because it is not within the scope of the core product, but could be addressed by an extension. The [VS Code Marketplace](https://marketplace.visualstudio.com/vscode) lists existing extensions. See also [Extending VS Code](https://code.visualstudio.com/docs/extensions/overview) and our [issue tracking](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md) guidelines.\n\nThank you for your contributions."
        },
        {
            type: 'label',
            name: 'not-reproducible',
            executeForExistingLabels: false,
            action: 'close',
            comment: "This issue has been closed because the problem could not be reproduced either because it is already fixed in later versions of the product or because it requires additional details on how to reproduce it. See also our [issue tracking](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md) guidelines.\n\nThank you for your contributions."
        },
        {
            type: 'label',
            name: 'out-of-scope',
            executeForExistingLabels: false,
            action: 'close',
            comment: "This issue has been closed because the feature it requests is not within the scope of the product. See also our [issue tracking](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md) guidelines.\n\nThank you for your contributions."
        },
        ################### Work in progress ###################
        {
            type: 'label',
            name: 'integrated-terminal',
            allowTriggerByBot: true,
            action: 'updateLabels',
            addLabel: 'confirmation-needed'
        },
        {
            type: 'label',
            name: 'confirmation-needed',
            allowTriggerByBot: true,
            action: 'comment',
            comment: "Our issue tracking requires confirmation by a second community member. Anyone but OP can do so by adding a comment `/confirm`. See also our [issue tracking](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md) guidelines.\n\nThank you for your contributions."
        },
        {
            type: 'comment',
            name: 'confirm',
            action: 'updateLabels',
            removeLabel: 'confirmation-needed',
            addLabel: 'confirmed'
        },
    ]
}
