language: node_js
node_js:
  - "node"
env:
  - no=1 fail=false
  - no=2 fail=false
  - no=3 fail=true label=hygiene
notifications:
  email: false
  webhooks:
    - http://vscode-probot.westus.cloudapp.azure.com:3450/travis/notifications
    - http://vscode-test-probot.westus.cloudapp.azure.com:3450/travis/notifications