language: node_js
node_js:
  - "node"
env:
  - fail=true
  - fail=false
  - label=hygiene
notifications:
  email: false
  webhooks:
    - http://vscode-probot.westus.cloudapp.azure.com:3450/travis/notifications
    - http://vscode-test-probot.westus.cloudapp.azure.com:3450/travis/notifications