language: node_js
node_js:
  - "node"
env:
  - no=1 fail=false
  - no=2 fail=true
  - no=3 fail=false label=hygiene
notifications:
  email: false
  webhooks:
    - https://vscode-probot.westus.cloudapp.azure.com:7890/travis/notifications
    - https://vscode-test-probot.westus.cloudapp.azure.com:7890/travis/notifications